stages:
  - build
  - static code
  - test

image: python:3.7.12

before_script:
  - python -V  # Print out python version for debugging
  - python -m pip install --upgrade pip
  - python -m pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

# Initialize template for standard image building
# We need to add locale support for french and english
.build: &build
  - python -m pip install .

build:
  stage: build
  script: *build

flake8:
  stage: static code
  script:
    - *build
    - python -m pip install flake8
    - flake8 stationverification

mypy:
  stage: static code
  script:
    - *build
    - python -m pip install mypy
    - mypy --install-type --non-interactive --ignore-missing-imports stationverification/

# pytest:
#   stage: test
#   variables:
#     SHAKEMAP_DYFI_MONGODB: mongodb://apache:apache@mongo-e1:27017,mongo-e2:27017,mongo-e3:27017/eqcan?replicaSet=chis-east
#     SHAKEMAP_FDSNWS: https://www.earthquakescanada.nrcan.gc.ca/
#   script:
#     - *build
#     - python -m pip install pytest pytest-cov pytest-socket
#     - pytest tests/* --log-level=DEBUG -k 'not test_shake'
#   coverage: '/TOTAL.*\s+(\d+%)$/'
#   artifacts:
#     reports:
#       cobertura: coverage.xml
#     paths:
#       - coverage.xml
